SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Build and flash the BLE HCI controller image to the network core
SB_CONFIG_NETCORE_IPC_RADIO=y
SB_CONFIG_NETCORE_IPC_RADIO_BT_HCI_IPC=y

# Add B0n image (bootloader for netcore)
SB_CONFIG_SECURE_BOOT_NETCORE=y

# # Set up multiple partitions for simultanious app and net core updating
SB_CONFIG_MCUBOOT_UPDATEABLE_IMAGES=2
SB_CONFIG_MCUBOOT_NRF53_MULTI_IMAGE_UPDATE=y

# # Enable support for netcore DFU
SB_CONFIG_NETCORE_APP_UPDATE=y

# # Simultaneous FOTA does not support rollback ("test" feature)
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

# Build merged hex images for both cores
SB_CONFIG_MERGED_HEX_FILES=y